### ISSUE TITLE
Crashes When Changing Detail Window Size [BUG]

### ISSUE THREAD

**Issue by HungryCow212** [FSGModding/FSG_Mod_Assistant#14]
**Describe the bug**
When attempting to change the default detail window size in the user preferences an exception is raised and the program closes upon acceptance.

**To Reproduce**
1. Go to user preferences
2. Attempt to change "Window Width" to 1000
3. Tab or click away from the text box

**Expected behavior**
The program should accept the value and also allow the Window Height to be changed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Main window default size was changed without issue.

Crash Log:
[crash.log](https://github.com/FSGModding/FSG_Mod_Assistant/files/10031831/crash.log)

**Comment by jtsage** [comment]
Hah.  Turns out, it errors on the main window too (for me anyway).  I'm gonna spend a bit of today seeing if I can get it to just remember window size and placement instead of the explicit options - more so since that "detail" is used all over the place, and there is another set of sizes that isn't even in there.

Thanks for the report!

**Comment by HungryCow212** [comment]
No problem.  Great work so far, by the way!  I've wanted to make something similar to this for quite a while now, but haven't got around to it.

**Comment by jtsage** [comment]
Fixed in 1.2.2, release in a few minutes.
