### ISSUE TITLE
[BUG] Update Notification Dialog - Multiple Issues With the Dialog

### ISSUE THREAD

**Issue by Dylan-M** [FSGModding/FSG_Mod_Assistant#22]
**Describe the bug**
The update dialog will pull you out of other apps, even full screen games, when it pops up. Focus grab is apparently set.
Additionally, it does not say anything about what app it is referring to, it just says the "app" is ready for update. See screenshot.

**To Reproduce**
1. Keep the app open
2. Play FS22
3. Have an update come in while you're performing step 2.
4. You will be pulled out of FS22, and it will be force minimized, by the focus grab of the dialog.
5. You'll be confused about what is requesting permission to update due to the lack of info on the dialog.

**Expected behavior**
Dialog is modal, but does not grab focus.
Dialog includes pertinent info.

**Screenshots**
![Bad Upgrade Notification](https://user-images.githubusercontent.com/545408/206080487-d58f2094-011f-4242-88ad-1679246585e9.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
N/A

**Comment by Dylan-M** [comment]
As an addendum that I just realized, it would be nice if it was asking permission to download it, rather than just permission to install.

**Comment by jtsage** [comment]
As to the focus pull - I will see what I can do on this.  I'm not sure, but hopefully.

As to asking permission - again, I'll look into this, but I don't have a great deal of hope on it - there is some customization available to the updater, but not a whole lot.  I could possibly add a preference for it to check or not check, but the updater has to run *very* early in the app, much sooner than preferences are loaded, so that may be a dead end.
