### ISSUE TITLE
[BUG] Progress bar not working

### ISSUE THREAD

**Issue by DanL58** [FSGModding/FSG_Mod_Assistant#32]
The new progress bar is a nice feature but not working accurately. The progress bar shows complete even when scanning is still in process.

**Comment by jtsage** [comment]
Well....  sort of.  The issue is that the total mods to scanned is updated per-folder, so the "done" bit is a moving target. So, if you have for instance 10 folders of 100 mods each, the "done" amount will be 100, 200, 300, etc as it hits each folder.  I suppose I could re-work the scan to count all of the files first.  Lemme look at this.
