### ISSUE TITLE
Mod Processing on App Start up

### ISSUE THREAD

**Issue by ScootersWorkbench** [FSGModding/FSG_Mod_Assistant#56]
Can processing mods be made configurable?   Having many mod folders and unzipped mods the application takes too long to start up.   Right now I only have 3 mod folders in the configuration (of out of about 25) with currently only  ~1000 mods,  the application takes over 30 mins to process the mods and when I want to just quickly switch folders I can't.   Can this feature only process mods when you "open / expand" a different Mod folder than currently selected?   or have a way to see what has been processed and what is new but not interrogate every mod each time.   Maybe have a "dirty" flag that can be then triggered by the user to run a mod update?   I love this app,  but it's becoming unusable. :(    I hesitate to add the rest of my mod folders in or I won't be able to switch and play the game.   Not sure if this is causing problems,  but all of my mod folders are on OneDrive and sync between 2 different machines,  a dev machine and my gaming machine.   Also,  when an update runs the whole process starts over again.   

Thanks,
Scooter

**Comment by jtsage** [comment]
Let me do some thinking on this. My gut says, yes, OneDrive is the problem - this does indeed cache results.  It uses the file name + file date.  And I would guess that onedrive is updating the file data.  So, let me think on this and maybe come up with a better way

**Comment by jtsage** [comment]
Still working through this.  Just so I'm aware, are your computers joined to a windows domain?  I'm just trying to figure out why it's invalidating the cache.

As I mentioned, I use file name (full path) and file modified time.  There are reports that onedrive messes with the modified time, I'll look at adding an option to use creation date instead, but it will come with a couple of pitfalls - namely, if you *EDIT* a zip file you are working on (not make a new one like I usually do), the updates won't show in the assistant.  But it might be about the only option I have available.  

The slowdown on reading mods is because we need at least some basic information to display, so defering it until open isn't an option that will work.  And ZIP files are an inefficient structure.  That said, I did a bunch of profiling today and got the load time to maybe 25% of what it was, perhaps even less.

**Comment by jtsage** [comment]
![2023-01-29 15_46_34-User Preferences](https://user-images.githubusercontent.com/605986/215354917-df8d5921-7e1a-415a-9238-6dca8ac99612.png)

**Comment by ScootersWorkbench** [comment]
My machines are not on a domain,  just a private network at home.

**Comment by jtsage** [comment]
Awesome, thanks. I'm interested to see if / how well the added feature above works for you - I'm pausing for a few hours to give my very on top of things translator a bit of time, and then I'll push that update out.

**Comment by ScootersWorkbench** [comment]
This feature is so nice now and it's so much faster.    This app is really the best thing since sliced bread!    Keep up the great work.   I can't believe how much I needed this tool!
