### ISSUE TITLE
[BUG] "Check Versions" option - bad version detection

### ISSUE THREAD

**Issue by KITT3000** [FSGModding/FSG_Mod_Assistant#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After using the "Check Versions" option, it detects an incorrect current version. From my observations, it checks the final number and if it is larger, it considers it a newer version, and it should check each of the 4 elements and if one of them starts to differ (it will be a higher number) it should be considered the latest version.
![image](https://user-images.githubusercontent.com/2678653/218176524-a2f6f93c-246c-42fa-b062-e91727674841.png)
![image](https://user-images.githubusercontent.com/2678653/218176616-556f8bfa-a9d3-4dd6-a768-9b86a244fce0.png)

### Environment

```markdown
- Mod Assistant Version: 2.0.9
- OS: Win10 22H2
- Virtualized: No
```

**Comment by jtsage** [comment]
Grrr.  This one bugs me.  I can't begin to say how many really good libraries are available the compare semver versions.  But of course, these *are not* semver, just sorta close.  Thanks for catching this :)  (of note, this also has to be able to call back on simple string comparison, because "Beta-0.1" is a totally valid version so far as the game is concerned, even if they won't let it on modhub)

**Comment by jtsage** [comment]
Turns out I was only doing half the comparison.  If it would have grabbed the `7.1.2.3` CP version first, it would have detected that `2` is bigger than `1` and set the "best" version to `7.2.0.0` - but when it grabbed `7.2.0.0`, `1` isn't less than `2`, but the `2` of `7.1.2.3` is bigger than `0`, so it reset it.  Both directions covered now. Thanks again.

**Comment by jtsage** [comment]
closing as complete
